eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  application:
    name: employee-core-service
  datasource:
    url: jdbc:mysql://team-project.cjfqfrgtvaw0.us-east-1.rds.amazonaws.com/info
    username: admin
    password: beaconfire
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        enable_lazy_load_no_trans: true
# spring:
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: "guest"
#   cloud:
#     bus:
#       enabled: true
#       refresh:
#         enabled: true
#   zipkin:
#     base-url: http://localhost:9411/
#   sleuth:
#     sampler:
#       probability: 1

# logstash:
#   host: localhost
#   port: 5000

# region:
#   state: MA
